Repository InHyeok-J/relay-mind-web, pull requests merged in 2021-12, with the labels that each got.

#20 Feat/16 : 게임 방 생성 및 레디스
  back/docker-compose.yml
  back/package-lock.json
  back/package.json
  back/src/configs/index.ts
  back/src/controllers/game/createGame.ts
  back/src/controllers/game/getGame.ts
  back/src/controllers/game/getGameList.ts
  back/src/controllers/game/index.ts
  back/src/controllers/user/login.ts
  back/src/controllers/user/logout.ts
  back/src/controllers/user/signUp.ts
  back/src/database/ormconfig.ts
  back/src/database/redisClient.ts
  back/src/entity/Game.ts
  back/src/entity/Player.ts
  back/src/entity/User.ts
  back/src/entity/Validation.ts
  back/src/index.ts
  back/src/middleware/errorHandler.ts
  back/src/routes/404.ts
  back/src/routes/game.ts
  back/src/routes/index.ts
  back/src/routes/user.ts
  back/src/utils/customError.ts
  back/tsconfig.json
Labels: Feature⭐️, BackEnd ❗️

#25 Feat: Socket 셋팅
  back/package-lock.json
  back/package.json
  back/src/app.ts
  back/src/configs/passport/index.ts
  back/src/controllers/game/createGame.ts
  back/src/controllers/user/login.ts
  back/src/controllers/user/signUp.ts
  back/src/entity/Game.ts
  back/src/index.ts
  back/src/socket.ts
  back/src/types/index.d.ts
Labels: Feature⭐️, BackEnd ❗️

#26 Feat/24 프론트 소켓 셋팅 및 방 입장
  back/src/controllers/game/checkGamePassword.ts
  back/src/controllers/game/index.ts
  back/src/routes/game.ts
  back/src/socket.ts
  back/tsconfig.json
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/api/gameApi.js
  front/src/index.js
  front/src/module/game.js
  front/src/pages/Lobby.js
  front/src/pages/Main.js
  front/src/pages/components/PasswordCheckModal.js
  front/src/pages/components/RegisterModal.js
  front/src/pages/components/RoomComponent.js
  front/src/pages/components/RoomListComponent.js
  front/src/setUpProxy.js
  front/src/utils/authCheck.js
  front/yarn.lock
Labels: Feature⭐️, BackEnd ❗️, FrontEnd ❗️

#28 Fix: 소켓 예외처리 추가
  back/src/socket.ts
  front/src/pages/Lobby.js
Labels: Bug❗️

#31 Feat/30 게임 입장 나가기 / 시작 버튼
  back/src/controllers/game/createGame.ts
  back/src/index.ts
  back/src/socket.ts
  back/src/utils/redisAsync.ts
  front/package-lock.json
  front/src/App.js
  front/src/api/gameApi.js
  front/src/module/game.js
  front/src/module/index.js
  front/src/module/socket.js
  front/src/pages/GameRoom.js
  front/src/pages/Lobby.js
  front/src/pages/components/CreateRoomModal.js
  front/src/pages/components/PasswordCheckModal.js
  front/src/pages/components/RoomComponent.js
  front/src/pages/components/RoomListComponent.js
  front/src/setUpProxy.js
  front/src/utils/authCheck.js
  front/yarn.lock
Labels: Feature⭐️

#34 Feat: Mock-data로 마이페이지 구현
  front/src/App.js
  front/src/pages/Lobby.js
  front/src/pages/MyPage.js
  front/src/pages/components/DetailGameComponent.js
  front/src/pages/components/GameComponent.js
  front/src/pages/components/PlayedGameList.js
Labels: Feature⭐️, FrontEnd ❗️

#35 Feat/32 그림그리기 최종 기능, 프로필 기능
  back/src/controllers/game/createGame.ts
  back/src/controllers/game/drawKeyword.ts
  back/src/controllers/game/getGame.ts
  back/src/controllers/game/index.ts
  back/src/controllers/game/keywordUpdate.ts
  back/src/controllers/game/startGame.ts
  back/src/controllers/user/index.ts
  back/src/controllers/user/profile.ts
  back/src/entity/Draw.ts
  back/src/entity/Game.ts
  back/src/entity/Player.ts
  back/src/entity/User.ts
  back/src/routes/game.ts
  back/src/routes/user.ts
  back/src/socket.ts
  back/src/utils/redisAsync.ts
  front/src/App.css
  front/src/App.js
  front/src/api/gameApi.js
  front/src/api/userApi.js
  front/src/module/game.js
  front/src/module/user.js
  front/src/pages/GameRoom.js
  front/src/pages/Lobby.js
  front/src/pages/MyPage.js
  front/src/pages/PlayGame.js
  front/src/pages/components/CreateRoomModal.js
  front/src/pages/components/DetailGameComponent.js
  front/src/pages/components/GameComponent.js
  front/src/pages/components/GameEnd.js
  front/src/pages/components/KeywordSendModal.js
  front/src/pages/components/Sketch.js
Labels: Feature⭐️, BackEnd ❗️, FrontEnd ❗️

#36 docs: READMD.md 문서 작성
  Readme.md
Labels: documentation
