Repository InHyeok-J/relay-mind-web, pull requests merged in 2021-11, with the labels that each got.

#8 Feat/1 : 백엔드 기본 셋팅
  back/.babelrc
  back/.eslintrc
  back/.gitignore
  back/package-lock.json
  back/package.json
  back/src/app.js
  back/src/app.ts
  back/src/configs/index.js
  back/src/configs/index.ts
  back/src/configs/passport/index.ts
  back/src/configs/passport/localStrategy.ts
  back/src/controllers/TestController.js
  back/src/controllers/index.ts
  back/src/database/ormconfig.ts
  back/src/entity/User.ts
  back/src/index.ts
  back/src/middleware/errorHandler.ts
  back/src/middlewares/ErrorHandler.js
  back/src/routes/user.ts
  back/src/services/TestService.js
  back/tsconfig.json
Labels: Feature⭐️

#9 Feat/6 인증관련 API
  back/package-lock.json
  back/package.json
  back/src/configs/passport/index.ts
  back/src/configs/passport/localStrategy.ts
  back/src/controllers/index.ts
  back/src/controllers/user/getUser.ts
  back/src/controllers/user/index.ts
  back/src/controllers/user/login.ts
  back/src/controllers/user/logout.ts
  back/src/controllers/user/signUp.ts
  back/src/entity/User.ts
  back/src/index.ts
  back/src/middleware/authHandler.ts
  back/src/middleware/errorHandler.ts
  back/src/routes/index.ts
  back/src/routes/user.ts
  back/src/types/index.d.ts
  back/src/utils/catchAsync.ts
  back/src/utils/customReponse.ts
  back/tsconfig.json
Labels: Feature⭐️, BackEnd ❗️

#10 Feature:docker setting
  back/.dockerignore
  back/Dockerfile
  back/docker-compose.yml
  back/package-lock.json
  back/package.json
  back/src/configs/index.ts
  back/src/database/ormconfig.ts
  back/src/index.ts
Labels: Feature⭐️, BackEnd ❗️

#12 Fix: 회원가입 중복검사 오타 수정
  back/src/controllers/user/signUp.ts
Labels: Bug❗️, BackEnd ❗️

#13 Feat/5 메인페이지 개발
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/App.css
  front/src/App.js
  front/src/api/userApi.js
  front/src/assets/Bg_paperTexture.jpg
  front/src/assets/RM_FullLogo.png
  front/src/assets/RM_ShortLogo.png
  front/src/components/CustomButton.js
  front/src/components/CustomInput.js
  front/src/hooks/useInput.js
  front/src/index.js
  front/src/module/index.js
  front/src/module/test.js
  front/src/module/user.js
  front/src/pages/Main.js
  front/src/pages/components/LoginModal.js
  front/src/pages/components/MainModal.js
  front/src/pages/components/RegisterModal.js
  front/src/utils/RegExpCheck.js
Labels: Feature⭐️, FrontEnd ❗️
